## Linear Algebra: _Matrix Eigenvalue Problems_
Q. What's the idea behind Eigenvalues and Eigenvectors?<br>
A. Boring way of explining it is **Ax = (Lambda)x** (x is an unknown vector & lambda is an unknown scalar. But, let's visualize it. Given a set of points/vectors in a space, _eigenvectors_ are the points/vectors that stay on the same line after applying a transformtion **A** to it.<br>
EigenValues are of great interest to solving practical problems in Engineering, physics, analytics, etc. <br>
**Visualization of the Eigenvalues and Eigenvectors for a dataset**

Reference Book - Advanced Engineering Mathematics by Erwin Kreyszig (Chapter - 8) <br>

**Contents:**
- Eigenvalues and Eigenvectors
- Applications of Eigenvalues and Eigenvectors

In [2]:
import numpy as np

In [4]:
A = np.matrix('-5 2; 2 -2')

#Getting the EigenValues of a matrix
np.linalg.eig(A)

(array([-6., -1.]), matrix([[-0.89442719, -0.4472136 ],
         [ 0.4472136 , -0.89442719]]))

Eigenvalues of a square-matrix **A** are the roots of the **characteristics equation** (**A - (lambda)I**) = 0 <br>
Hence, an n x n matrix has atleast one eigenvalue and atmost n eigenvalue.

### Some applications of Eigenvalue Problems
1. Elastic Deformation/ Streching of an Elastic Memberane
2. Eigenvalue Problems Arising from Markiv Processes

In [8]:
# Elastic Deformation
# Q. 7 Find the principal direction of contraction and expansion
A = np.matrix('3 5; 5 3')
np.linalg.eig(A)

(array([ 8., -2.]), matrix([[ 0.70710678, -0.70710678],
         [ 0.70710678,  0.70710678]]))

In [11]:
np.linalg.eigh(A)

(array([-2.,  8.]), matrix([[-0.70710678,  0.70710678],
         [ 0.70710678,  0.70710678]]))

### Symmetric, Skew-Symmetric, and Orthogonal Matrices
#### Square matrix is required
1. Symmetric - if transpose of a square matric = matrix
2. Skew-Symmentric - if transpose of a square matric = - matrix
3. Orthogonal - Transpose of Matrix = inverse of Matrix

In [12]:
# Symmetric
S = np.matrix('-3 1 5;\
               1 0 -2;\
               5 -2 4')
S == np.transpose(S)

matrix([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]], dtype=bool)

In [13]:
# Skew-Symmetric
S = np.matrix('0 9 -12;\
               -9 0 20;\
               12 -20 0')
S == -1*np.transpose(S)

matrix([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]], dtype=bool)

In [19]:
# Orthogonal MAtrix
S = np.matrix('2/3 1/3 2/3;\
               -2/3 2/3 1/3;\
               1/3 2/3 -2/3')
print np.transpose(S), '\n',np.linalg.inv(S)

[[ 23 -23  13]
 [ 13  23  23]
 [ 23  13 -23]] 
[[ 0.01936027 -0.01936027  0.00841751]
 [ 0.00841751  0.01936027  0.01936027]
 [ 0.01936027  0.00841751 -0.01936027]]
